travis:
  secure:
    BINSTAR_TOKEN: abPH9S8k0MWVWFJj/ft8DVaY/xMVXlUtHwpdRadGWBjyP1plg4fbhrOzpFBDKJ3LnMc8wJl0tFyde+JBPmS5eTqpHVrTSeDmgmCZmE83vfKSrsKrTN+y7klsJsOqE7yX4C7UzOt+nXhao6EgpgEEM/3nxxsw3qrwUePKD08SxvBmVXjggpUrTdbs3DXcfaJLQkEb9RQjfB+rm79KSkGa1YtVBfFWN45seVyeng0hi1QdzeCJ+IFIkgtkBa9lSev3nQ+acQQIDBXdWG3F1TmtMKth5JqoMXB0zBIQ07Tnl0+JEpTRqf70in6roG4TPvbTUwpfzTsrpV5FXT9ugqhy8simg8SzJ5gWdE9exlKqktvxC9Gt6GHXWcVlAFkqbMz5vHstjV42HV7ryZEGYGHmis5zy9hPAAmDrrTWBJAbyiQX9KgjQ7wKcmXr9P64Ymn51EuCb3Q6Q5KFabxGmeiLJE8IKExMTYavc4w/Tn6mFQ6Gi9DPaeGQIwXDDRbWg/W2/2yryP1YmQRuXRBsgtjhVljmGJhTtfR47mtuqLMt2JFoVsKAZ7nhxqTPOdD6ISc+Uo6KU2i6Te5ohQo93vb//jLLWIK6hhUKxwmWO/lTz6ApmQH+RagdKxDXSCygtmIx0U5ooqaOuVwACsrxaPGZiy1pgfNnZ6REu9RRu+yiJ8A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
